# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 589)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadMatEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.loadMatEdit.setText("")
        self.loadMatEdit.setReadOnly(True)
        self.loadMatEdit.setObjectName("loadMatEdit")
        self.horizontalLayout_4.addWidget(self.loadMatEdit)
        self.loadMatBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMatBtn.sizePolicy().hasHeightForWidth())
        self.loadMatBtn.setSizePolicy(sizePolicy)
        self.loadMatBtn.setMinimumSize(QtCore.QSize(100, 23))
        self.loadMatBtn.setMaximumSize(QtCore.QSize(120, 23))
        self.loadMatBtn.setObjectName("loadMatBtn")
        self.horizontalLayout_4.addWidget(self.loadMatBtn)
        self.matLoadBox = QtWidgets.QCheckBox(self.centralwidget)
        self.matLoadBox.setMinimumSize(QtCore.QSize(72, 17))
        self.matLoadBox.setMaximumSize(QtCore.QSize(72, 17))
        self.matLoadBox.setChecked(True)
        self.matLoadBox.setObjectName("matLoadBox")
        self.horizontalLayout_4.addWidget(self.matLoadBox)
        self.matLoadDAT2p0 = QtWidgets.QCheckBox(self.centralwidget)
        self.matLoadDAT2p0.setObjectName("matLoadDAT2p0")
        self.horizontalLayout_4.addWidget(self.matLoadDAT2p0)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineFind = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFind.setObjectName("lineFind")
        self.horizontalLayout_2.addWidget(self.lineFind)
        self.regexCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.regexCheck.setObjectName("regexCheck")
        self.horizontalLayout_2.addWidget(self.regexCheck)
        self.linePath = QtWidgets.QLineEdit(self.centralwidget)
        self.linePath.setReadOnly(True)
        self.linePath.setObjectName("linePath")
        self.horizontalLayout_2.addWidget(self.linePath)
        self.dotFormatCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.dotFormatCheck.setObjectName("dotFormatCheck")
        self.horizontalLayout_2.addWidget(self.dotFormatCheck)
        self.colorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.colorsCheck.setObjectName("colorsCheck")
        self.horizontalLayout_2.addWidget(self.colorsCheck)
        self.index0Check = QtWidgets.QCheckBox(self.centralwidget)
        self.index0Check.setObjectName("index0Check")
        self.horizontalLayout_2.addWidget(self.index0Check)
        self.matCheckButton = QtWidgets.QPushButton(self.centralwidget)
        self.matCheckButton.setObjectName("matCheckButton")
        self.horizontalLayout_2.addWidget(self.matCheckButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.fieldsTree = QtWidgets.QTreeWidget(self.splitter_2)
        self.fieldsTree.setObjectName("fieldsTree")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.valuesTable = QtWidgets.QTableWidget(self.splitter)
        self.valuesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.valuesTable.setObjectName("valuesTable")
        self.valuesTable.setColumnCount(0)
        self.valuesTable.setRowCount(0)
        self.valuesTable.horizontalHeader().setStretchLastSection(False)
        self.valuesTable.verticalHeader().setVisible(False)
        self.valuesTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout.addWidget(self.splitter_2)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 904, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuOpenRecent = QtWidgets.QMenu(self.menuBar)
        self.menuOpenRecent.setObjectName("menuOpenRecent")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCompare = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/comp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompare.setIcon(icon1)
        self.actionCompare.setObjectName("actionCompare")
        self.toolBar.addAction(self.actionCompare)
        self.menuBar.addAction(self.menuOpenRecent.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "matViewer"))
        self.loadMatBtn.setText(_translate("MainWindow", "Load mat"))
        self.matLoadBox.setText(_translate("MainWindow", "mudp only"))
        self.matLoadDAT2p0.setText(_translate("MainWindow", "DAT2.0"))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.regexCheck.setText(_translate("MainWindow", "regex"))
        self.dotFormatCheck.setText(_translate("MainWindow", "dot format"))
        self.colorsCheck.setText(_translate("MainWindow", "colors"))
        self.index0Check.setText(_translate("MainWindow", "index 0"))
        self.matCheckButton.setText(_translate("MainWindow", "Check Mat"))
        self.fieldsTree.headerItem().setText(0, _translate("MainWindow", "Mat fields"))
        self.valuesTable.setSortingEnabled(False)
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuOpenRecent.setTitle(_translate("MainWindow", "Open Recent"))
        self.actionCompare.setText(_translate("MainWindow", "Compare"))
        self.actionCompare.setToolTip(_translate("MainWindow", "Open mat in new window to compare"))

import rc_rc
