# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'efsConfig.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(353, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EFsTree = QtWidgets.QTreeWidget(self.groupBox)
        self.EFsTree.setObjectName("EFsTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.EFsTree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        self.verticalLayout_2.addWidget(self.EFsTree)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DAT2p0_CheckBox = QtWidgets.QCheckBox(Dialog)
        self.DAT2p0_CheckBox.setCheckable(True)
        self.DAT2p0_CheckBox.setObjectName("DAT2p0_CheckBox")
        self.horizontalLayout_3.addWidget(self.DAT2p0_CheckBox)
        self.detailsBox = QtWidgets.QCheckBox(Dialog)
        self.detailsBox.setObjectName("detailsBox")
        self.horizontalLayout_3.addWidget(self.detailsBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.outputEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputEdit.setText("")
        self.outputEdit.setReadOnly(True)
        self.outputEdit.setObjectName("outputEdit")
        self.horizontalLayout.addWidget(self.outputEdit)
        self.outputBtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputBtn.sizePolicy().hasHeightForWidth())
        self.outputBtn.setSizePolicy(sizePolicy)
        self.outputBtn.setMinimumSize(QtCore.QSize(120, 23))
        self.outputBtn.setMaximumSize(QtCore.QSize(120, 23))
        self.outputBtn.setObjectName("outputBtn")
        self.horizontalLayout.addWidget(self.outputBtn)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.acceptBtn = QtWidgets.QPushButton(Dialog)
        self.acceptBtn.setObjectName("acceptBtn")
        self.horizontalLayout_2.addWidget(self.acceptBtn)
        self.rejectBtn = QtWidgets.QPushButton(Dialog)
        self.rejectBtn.setObjectName("rejectBtn")
        self.horizontalLayout_2.addWidget(self.rejectBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EFs Config"))
        self.groupBox.setTitle(_translate("Dialog", "Choose extensions:"))
        self.EFsTree.headerItem().setText(0, _translate("Dialog", "Event finders"))
        __sortingEnabled = self.EFsTree.isSortingEnabled()
        self.EFsTree.setSortingEnabled(False)
        self.EFsTree.topLevelItem(0).setText(0, _translate("Dialog", "AFL"))
        self.EFsTree.topLevelItem(1).setText(0, _translate("Dialog", "LKS"))
        self.EFsTree.topLevelItem(2).setText(0, _translate("Dialog", "OBJ"))
        self.EFsTree.topLevelItem(3).setText(0, _translate("Dialog", "TSR"))
        self.EFsTree.topLevelItem(4).setText(0, _translate("Dialog", "Failsafes"))
        self.EFsTree.topLevelItem(5).setText(0, _translate("Dialog", "DVL"))
        self.EFsTree.topLevelItem(6).setText(0, _translate("Dialog", "STATS"))
        self.EFsTree.setSortingEnabled(__sortingEnabled)
        self.DAT2p0_CheckBox.setText(_translate("Dialog", "DAT2.0"))
        self.detailsBox.setText(_translate("Dialog", "Write details into csv file"))
        self.groupBox_3.setTitle(_translate("Dialog", "Output path"))
        self.outputBtn.setText(_translate("Dialog", "Change path"))
        self.acceptBtn.setText(_translate("Dialog", "OK"))
        self.rejectBtn.setText(_translate("Dialog", "Cancel"))

